### ISSUE TITLE
SASS does not exist?

### ISSUE THREAD

**Issue by CKGrafico** [Degfy/vue-perfect-scrollbar#13]
File to import not found or unreadable: ~perfect-scrollbar/src/css/main.scss. -> https://github.com/utatti/perfect-scrollbar/tree/master/src

**Comment by eldarshmatkov** [comment]
Try to install older version of perfect-scrollbar, for example, cheers @CKGrafico 
npm install perfect-scrollbar@0.8.1 --save

**Comment by CKGrafico** [comment]
Yes I've fixed some days ago doing this I still think that the plugin has to be updated! isn't it?

**Comment by Binaryify** [comment]
you can use this
https://binaryify.github.io/vue-custom-scrollbar/en/

**Comment by thomascallahandell** [comment]
@Binaryify Thank you! Had yours up and running in about 2 minutes.

**Comment by douglasg14b** [comment]
@Binaryify  thanks! yours works as expected.
