### ISSUE TITLE
This doesn't work

### ISSUE THREAD

**Issue by david-saint** [Degfy/vue-perfect-scrollbar#19]
The package is outdated

**Comment by Binaryify** [comment]
you can use this 
https://binaryify.github.io/vue-custom-scrollbar/en/

**Comment by david-saint** [comment]
I got the default perfect scrollbar to work.

By importing it to the component that needs it then initializing it in the `mounted()`

**Comment by mercs600** [comment]
I did something simple what you can use as global component: https://github.com/mercs600/vue2-perfect-scrollbar
