### ISSUE TITLE
Scrolling using Vue methods

### ISSUE THREAD

**Issue by pawelmadeja** [Degfy/vue-perfect-scrollbar#2]
I'm wondering whether is it possible to scroll to sections by using Vue instance methods? I see that in the https://github.com/noraesae/perfect-scrollbar#how-to-use documentation there's information that it's possible to use 
```
container.scrollTop = 0;
Ps.update(container);
```

but how to use it with this plugin?

**Comment by Degfy** [comment]
<VuePerfectScrollbar ref="ps" other-attr="blabla"></VuePerfectScrollbar>

...
const ps = this.$refs.ps
ps.$el.scrollTop = 0
ps.update() //if you changed the container's size
...

**Comment by pawelmadeja** [comment]
thanks!
