### ISSUE TITLE
How to update scroll

### ISSUE THREAD

**Issue by paulotra** [Degfy/vue-perfect-scrollbar#22]
how do i update the scroll bar like `ps.update()`

**Comment by mercs600** [comment]
You can use this wrapper: https://github.com/mercs600/vue2-perfect-scrollbar then you can reach ps object by $refs

**Comment by nmaoez** [comment]
Why was this closed? So if we want to use `ps.update()` we need to use another project? Do I have to adjust all places in my project where I use vue-perfect-scrollbar and replace it with vue2-perfect-scrollbar? This not really nice... Isn't there a chance to introduce `ps.update()`?

**Comment by wildwest-service** [comment]
You can run `ps.update()`.

Try writing `<VuePerfectScrollbar ref="ps">`.
This gives you access to `this.$refs.ps.update()`.
