### ISSUE TITLE
Vue-router?

### ISSUE THREAD

**Issue by CKGrafico** [Degfy/vue-perfect-scrollbar#5]
If I add the component to the parent component in components{} I've this error `vue For recursive components, make sure to provide the "name" option.` but if I use as `Vue.component('vue-scroll', VuePerfectScrollbar);`on the root file (app.ts) is working well.

**Comment by Degfy** [comment]
are you sure that you have imported  vue-perfect-scrollbar or you can console.log

**Comment by CKGrafico** [comment]
Yes @Degfy

**Comment by Degfy** [comment]
@CKGrafico i had written an example with vuerouter(https://github.com/Degfy/vue-perfect-scrollbar#22-example-with-vuerouter), you can have a try.

**Comment by CKGrafico** [comment]
Thanks :D
