### ISSUE TITLE
v-model doesnt work inside VuePerfectScrollbar tags

### ISSUE THREAD

**Issue by gregorredinger** [Degfy/vue-perfect-scrollbar#6]
Hi it seems like v-model doesnt work inside VuePerfectScrollbar tags. The Scrollbar works great, but my departmentManipulator.name property stop changing after wrapping the form inside VuePerfectScrollbar Tags:

`<div xmlns:v-on="http://www.w3.org/1999/xhtml">

    
    <div xmlns:v-bind="http://www.w3.org/1999/xhtml" xmlns:v-on="http://www.w3.org/1999/xhtml">

        
        <div class="content_box" v-bind:style="{width: showOverlay == false ? '0rem' : '25rem'}">
            <VuePerfectScrollbar class="content_box" v-once :settings="settings">

            <button class="close_button" v-on:click="closeOverlay()">x</button>

            
            <div class="content">
                <i class="fa fa-building-o" aria-hidden="true"></i>
                <div class="input_help_text"> Bitte gib den Namen der Abteilung ein, welche du hinzufügen möchtest. </div>
                <input v-model="departmentManipulator.name" maxlength="70" placeholder= "" required>

                <button class="fab_execute_form" v-on:click="addDepartment()">+</button>
                <p> Add Department </p>
            </div>
            </VuePerfectScrollbar>

        </div>
        
        <div class="black_overlay" v-bind:style="{display: showOverlay == false ? 'none' : 'block'}"></div>
    </div>

    
    <button class="fab_add" v-on:click="showOverlayForm()">+</button>
    <button class="fab_edit"><i class="fa fa-wrench" aria-hidden="true"></i></button>
    <button class="fab_delete"><i class="fa fa-trash" aria-hidden="true"></i></button>
</div>`

**Comment by Degfy** [comment]
I think this must be caused by other problems,I used it in my own app many times without problem. You can send me more code, Maybe I could help you find the problem.

**Comment by gregorredinger** [comment]
Hi thanks for your offer, but i solved the problem. I changed 
`<VuePerfectScrollbar class="content_box" v-once :settings="settings"> ... </VuePerfectScrollbar>`
to
` <VuePerfectScrollbar class="content_box"> ... </VuePerfectScrollbar>`
and now it works without any problems. Although I dont know exactly why it works now :D
Btw thanks for your vue port of perfect scrollar :)

**Comment by lbineau** [comment]
@gregorredinger It is because of the [v-once directive](https://vuejs.org/v2/api/#v-once). This directive is meant to only compute the HTML once so what is inside the node is not reactive anymore.
